name = "blixel-ai"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[[compatibility_flags]]
# Flags necesarios para Astro
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

# Variables de entorno (opcional)
[vars]
# PUBLIC_WP_GRAPHQL_URL = "https://cms.blixel.es/graphql"